const EmployeeData = [
  {
    id: 1,
    FirstName: "John",
    LastName: "Doe",
    ID: "EMP001",
    Designation: "Software Engineer",
    JoiningDate: "2023-05-10",
    TeamLeader: "Team Lead A",
    Manager: "Manager X",
  },
  {
    id: 2,
    FirstName: "Jane",
    LastName: "Smith",
    ID: "EMP002",
    Designation: "UI/UX Designer",
    JoiningDate: "2023-06-15",
    TeamLeader: "Team Lead B",
    Manager: "Manager Y",
  },
  {
    id: 3,
    FirstName: "Michael",
    LastName: "Johnson",
    ID: "EMP003",
    Designation: "Data Analyst",
    JoiningDate: "2023-07-20",
    TeamLeader: "Team Lead C",
    Manager: "Manager Z",
  },
  {
    id: 4,
    FirstName: "Emily",
    LastName: "Brown",
    ID: "EMP004",
    Designation: "Marketing Manager",
    JoiningDate: "2023-08-25",
    TeamLeader: "Marketing Lead",
    Manager: "Head of Marketing",
  },
  {
    id: 5,
    FirstName: "David",
    LastName: "Jones",
    ID: "EMP005",
    Designation: "Financial Analyst",
    JoiningDate: "2023-09-30",
    TeamLeader: "Finance Lead",
    Manager: "CFO",
  },
  {
    id: 6,
    FirstName: "Sarah",
    LastName: "Williams",
    ID: "EMP006",
    Designation: "Product Manager",
    JoiningDate: "2023-10-05",
    TeamLeader: "Product Lead",
    Manager: "Head of Product",
  },
  {
    id: 7,
    FirstName: "James",
    LastName: "Anderson",
    ID: "EMP007",
    Designation: "Sales Executive",
    JoiningDate: "2023-11-10",
    TeamLeader: "Sales Lead",
    Manager: "Head of Sales",
  },
  {
    id: 8,
    FirstName: "Olivia",
    LastName: "Martinez",
    ID: "EMP008",
    Designation: "HR Coordinator",
    JoiningDate: "2023-12-15",
    TeamLeader: "HR Lead",
    Manager: "Head of HR",
  },
  {
    id: 9,
    FirstName: "Ethan",
    LastName: "Garcia",
    ID: "EMP009",
    Designation: "Graphic Designer",
    JoiningDate: "2024-01-20",
    TeamLeader: "Design Lead",
    Manager: "Creative Director",
  },
  {
    id: 10,
    FirstName: "Ava",
    LastName: "Lopez",
    ID: "EMP010",
    Designation: "Quality Assurance Engineer",
    JoiningDate: "2024-02-25",
    TeamLeader: "QA Lead",
    Manager: "Head of QA",
  },
  {
    id: 11,
    FirstName: "William",
    LastName: "Hernandez",
    ID: "EMP011",
    Designation: "Business Analyst",
    JoiningDate: "2024-03-10",
    TeamLeader: "Business Lead",
    Manager: "Head of Business",
  },
  {
    id: 12,
    FirstName: "Sophia",
    LastName: "King",
    ID: "EMP012",
    Designation: "System Administrator",
    JoiningDate: "2024-04-15",
    TeamLeader: "SysAdmin Lead",
    Manager: "IT Manager",
  },
  {
    id: 13,
    FirstName: "Alexander",
    LastName: "Scott",
    ID: "EMP013",
    Designation: "Customer Support Specialist",
    JoiningDate: "2024-05-20",
    TeamLeader: "Support Lead",
    Manager: "Support Manager",
  },
  {
    id: 14,
    FirstName: "Mia",
    LastName: "Green",
    ID: "EMP014",
    Designation: "Operations Manager",
    JoiningDate: "2024-06-25",
    TeamLeader: "Ops Lead",
    Manager: "Operations Director",
  },
  {
    id: 15,
    FirstName: "Daniel",
    LastName: "Baker",
    ID: "EMP015",
    Designation: "Project Manager",
    JoiningDate: "2024-07-30",
    TeamLeader: "Project Lead",
    Manager: "Project Director",
  },
  {
    id: 16,
    FirstName: "Amelia",
    LastName: "Young",
    ID: "EMP016",
    Designation: "Research Analyst",
    JoiningDate: "2024-08-05",
    TeamLeader: "Research Lead",
    Manager: "Research Director",
  },
  {
    id: 17,
    FirstName: "Benjamin",
    LastName: "Harris",
    ID: "EMP017",
    Designation: "Technical Writer",
    JoiningDate: "2024-09-10",
    TeamLeader: "Writing Lead",
    Manager: "Editor-in-Chief",
  },
  {
    id: 18,
    FirstName: "Charlotte",
    LastName: "Clark",
    ID: "EMP018",
    Designation: "Event Coordinator",
    JoiningDate: "2024-10-15",
    TeamLeader: "Event Lead",
    Manager: "Event Manager",
  },
  {
    id: 19,
    FirstName: "Henry",
    LastName: "Lewis",
    ID: "EMP019",
    Designation: "Accountant",
    JoiningDate: "2024-11-20",
    TeamLeader: "Accounting Lead",
    Manager: "Accounting Manager",
  },
  {
    id: 20,
    FirstName: "Grace",
    LastName: "Adams",
    ID: "EMP020",
    Designation: "Customer Success Manager",
    JoiningDate: "2024-12-25",
    TeamLeader: "CSM Lead",
    Manager: "Customer Success Director",
  },
];

export default EmployeeData;
